






















});    });        expect(result.settings).toEqual(settings);        const result = await chrome.storage.sync.get('settings');        await chrome.storage.sync.set({ settings });        };            refreshInterval: 30            },                gradeImpact: 0.3                gradeWeight: 0.3,                dueDate: 0.4,            priorities: {            icalUrl: 'https://example.com/calendar.ics',        const settings = {    test('saves settings correctly', async () => {    });        chrome.storage.sync.clear();    beforeEach(() => {describe('Settings Management', () => {import { chrome } from 'jest-chrome';